### ISSUE TITLE
Sound issue for new migi build

### ISSUE THREAD

**Issue by roccoishot** [ZooLSmith/MIGI3#2]
While I was using migi I noticed the old sounds were placed in automatically. When I ran the game the r8 revolver made no sounds along with some knifes. I am not using custom sounds while this is happening and I have tried using my own sounds but the stock sounds override. Pls fix zool.

**Comment by ZooLSmith** [comment]
Hey, this sounds more like an addon problem than an issue with the tool. Can you send a zip of that folder?

[Alternatively, join the discord as it's easier to handle those issues there.](https://discordapp.com/invite/UmE9JG7)

**Comment by roccoishot** [comment]
I have to send in a anonfiles link because it is over 10 mb 
https://anonfiles.com/L2H1Vbvdu0/addons_zip

**Comment by ZooLSmith** [comment]
p_taser_darkages is what breaks it all, it has a "game_sounds_weapons.txt" file which essentially replaces the official one.
This addon is likely from before the R8 and wasn't meant for MIGI.

**Comment by roccoishot** [comment]
Thank you
